services:
  db:
    image: postgres:13
    container_name: postgres_service
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: mydatabase
    ports:
      - "5432:5432"
    volumes:
      - pg_data:/var/lib/postgresql/data

  rabbit:
    image: rabbitmq:3-management
    container_name: rabbitmq_service
    environment:
      RABBITMQ_DEFAULT_USER: admin
      RABBITMQ_DEFAULT_PASS: password
      RABBITMQ_SERVER_START_ARGS: "--wait"
    healthcheck:
      test: ["CMD", "rabbitmq-diagnostics", "check_running"]
      interval: 5s
      timeout: 10s
      retries: 10
    ports:
      - "5672:5672"
      - "15672:15672"
    volumes:
      - rabbit_data:/var/lib/rabbitmq

  main-app:
    build:
      context: .
      dockerfile: main-module/Dockerfile
    container_name: main_app
    volumes:
      - ./logs:/app/logs
      - ./.env:/app/.env:ro
    ports:
      - "727:727"
    depends_on:
      - db
      - rabbit
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/mydatabase
      SPRING_DATASOURCE_USERNAME: user
      SPRING_DATASOURCE_PASSWORD: password
      SPRING_JPA_HIBERNATE_DDL_AUTO: create-drop

  google-module:
    build:
      context: .
      dockerfile: google-module/Dockerfile
    container_name: google_service
    depends_on:
      rabbit:
        condition: service_healthy
    volumes:
      - ./logs:/app/logs
      - ./.env:/app/.env:ro
      - ./google_credentials.json:/app/google_credentials.json:ro
    environment:
      RABBITMQ_HOST: rabbit
      RABBITMQ_PORT: 5672
      RABBITMQ_USERNAME: admin
      RABBITMQ_PASSWORD: password

  prometheus:
    image: prom/prometheus
    container_name: prometheus_service
    ports:
      - "9090:9090"
    depends_on:
      - main-app
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml

  grafana:
    image: grafana/grafana
    container_name: grafana_service
    ports:
      - "3000:3000"
    volumes:
      - grafana_data:/var/lib/grafana
    depends_on:
      - prometheus

volumes:
  pg_data:
  rabbit_data:
  grafana_data:
