services:
  db:
    image: postgres:13
    container_name: postgres_service
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: mydatabase
    ports:
      - "5432:5432"
    volumes:
      - pg_data:/var/lib/postgresql/data

  rabbit:
    image: rabbitmq:3-management
    container_name: rabbitmq_service
    environment:
      RABBITMQ_DEFAULT_USER: admin
      RABBITMQ_DEFAULT_PASS: password
      RABBITMQ_SERVER_START_ARGS: "--wait"
    healthcheck:
      test: ["CMD", "rabbitmq-diagnostics", "check_running"]
      interval: 5s
      timeout: 10s
      retries: 10
    ports:
      - "5672:5672"
      - "15627:15627"
    volumes:
      - rabbit_data:/var/lib/rabbitmq

  main-app:
    build:
      context: .
      dockerfile: main-module/Dockerfile
    container_name: main_app
    volumes:
      - ./logs:/app/logs
      - ./.env:/app/.env:ro
    ports:
      - "727:727"
    depends_on:
      - db
      - rabbit
      - otel-collector
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/mydatabase
      SPRING_DATASOURCE_USERNAME: user
      SPRING_DATASOURCE_PASSWORD: password
      MANAGEMENT_OTLP_TRACING_ENDPOINT: http://otel-collector:4317

  google-module:
    build:
      context: .
      dockerfile: google-module/Dockerfile
    container_name: google_service
    depends_on:
      rabbit:
        condition: service_healthy
    volumes:
      - ./logs:/app/logs
      - ./.env:/app/.env:ro
      - ./google_credentials.json:/app/google_credentials.json:ro
    ports:
      - "8080:8080"
    environment:
      RABBITMQ_HOST: rabbit
      RABBITMQ_PORT: 5672
      RABBITMQ_USERNAME: admin
      RABBITMQ_PASSWORD: password

  frontend:
    build:
      context: ./react-refactoring
      dockerfile: Dockerfile
    container_name: frontend_service
    ports:
      - "5173:5173"
    volumes:
      - ./react-refactoring:/app
      - /app/node_modules
    depends_on:
      - main-app

  prometheus:
    image: prom/prometheus
    container_name: prometheus_service
    ports:
      - "9090:9090"
    depends_on:
      - main-app
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml

  grafana:
    image: grafana/grafana
    container_name: grafana_service
    ports:
      - "3000:3000"
    volumes:
      - grafana_data:/var/lib/grafana
      - ./grafana/provisioning:/etc/grafana/provisioning:ro
      - ./grafana/dashboards:/opt/grafana/dashboards:ro
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=admin
      - GF_SECURITY_ADMIN_USER=admin
      - GF_INSTALL_PLUGINS=
      - GF_PATHS_PROVISIONING=/etc/grafana/provisioning
      - GF_DASHBOARDS_DEFAULT_HOME_DASHBOARD_PATH=/opt/grafana/dashboards/main-service-dashboard.json
    user: "472:472"
    depends_on:
      - prometheus

  jaeger:
    image: jaegertracing/all-in-one:1.57
    container_name: jaeger_service
    ports:
      - "16686:16686"
      - "4317:4317"
      - "4318:4318"
    environment:
      - COLLECTOR_OTLP_ENABLED=true

  otel-collector:
    image: otel/opentelemetry-collector-contrib:0.102.0
    container_name: otel_collector_service
    command: [ "--config=/etc/otel-collector-config.yaml" ]
    volumes:
      - ./otel-collector-config.yaml:/etc/otel-collector-config.yaml
    ports:
      - "4319:4317"
      - "4320:4318"
    depends_on:
      - jaeger

volumes:
  pg_data:
  rabbit_data:
  grafana_data:
