global:
  scrape_interval: 5s

scrape_configs:
  - job_name: 'spring-app'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: ['main-app:727']

  - job_name: 'google-module'
    static_configs:
       - targets: ['google-module:8080']
